// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Pole_Id_Tabela_Password : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pole_Id_Tabela_Password));
        
        string IMigrationMetadata.Id
        {
            get { return "201501070006122_Pole_Id_Tabela_Password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
