// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Zmiana_nazwy_encji : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zmiana_nazwy_encji));
        
        string IMigrationMetadata.Id
        {
            get { return "201501122237535_Zmiana_nazwy_encji"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
