//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbEntity", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.MenuItemCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.MenuItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.Table))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.MenuItemQuantity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.UserContext))]
    public partial class DbEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItemCategory", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    public partial class MenuItemCategory : WebApplication1.ServiceReference1.DbEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    public partial class MenuItem : WebApplication1.ServiceReference1.DbEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference1.MenuItemCategory CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference1.Money PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference1.MenuItemCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference1.Money Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Table", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    public partial class Table : WebApplication1.ServiceReference1.DbEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    public partial class Order : WebApplication1.ServiceReference1.DbEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClosingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference1.MenuItemQuantity[] MenuItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PlacingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference1.Table TableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference1.UserContext WaiterField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClosingDate {
            get {
                return this.ClosingDateField;
            }
            set {
                if ((this.ClosingDateField.Equals(value) != true)) {
                    this.ClosingDateField = value;
                    this.RaisePropertyChanged("ClosingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference1.MenuItemQuantity[] MenuItems {
            get {
                return this.MenuItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemsField, value) != true)) {
                    this.MenuItemsField = value;
                    this.RaisePropertyChanged("MenuItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PlacingDate {
            get {
                return this.PlacingDateField;
            }
            set {
                if ((this.PlacingDateField.Equals(value) != true)) {
                    this.PlacingDateField = value;
                    this.RaisePropertyChanged("PlacingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference1.Table Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference1.UserContext Waiter {
            get {
                return this.WaiterField;
            }
            set {
                if ((object.ReferenceEquals(this.WaiterField, value) != true)) {
                    this.WaiterField = value;
                    this.RaisePropertyChanged("Waiter");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItemQuantity", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    public partial class MenuItemQuantity : WebApplication1.ServiceReference1.DbEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReference1.MenuItem MenuItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReference1.MenuItem MenuItem {
            get {
                return this.MenuItemField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemField, value) != true)) {
                    this.MenuItemField = value;
                    this.RaisePropertyChanged("MenuItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserContext", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    public partial class UserContext : WebApplication1.ServiceReference1.DbEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Money", Namespace="http://schemas.datacontract.org/2004/07/ClassLib.DbDataStructures")]
    [System.SerializableAttribute()]
    public partial class Money : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IManagerDataAccessWCFService")]
    public interface IManagerDataAccessWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/LogIn", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/LogInResponse")]
        WebApplication1.ServiceReference1.UserContext LogIn([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/LogIn", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/LogInResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext> LogInAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/LogOut", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/LogOutResponse")]
        bool LogOut(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/LogOut", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/LogOutResponse")]
        System.Threading.Tasks.Task<bool> LogOutAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItemCategories", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItemCategoriesResponse")]
        WebApplication1.ServiceReference1.MenuItemCategory[] GetMenuItemCategories(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItemCategories", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItemCategoriesResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItemCategory[]> GetMenuItemCategoriesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItems", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItemsResponse")]
        WebApplication1.ServiceReference1.MenuItem[] GetMenuItems(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItems", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/GetMenuItemsResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItem[]> GetMenuItemsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/GetTables", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/GetTablesResponse")]
        WebApplication1.ServiceReference1.Table[] GetTables(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseDataAccessWCFService/GetTables", ReplyAction="http://tempuri.org/IBaseDataAccessWCFService/GetTablesResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Table[]> GetTablesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddManager", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddManagerResponse")]
        WebApplication1.ServiceReference1.UserContext AddManager(string firstName, string lastName, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddManager", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddManagerResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext> AddManagerAsync(string firstName, string lastName, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItemCategory", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItemCategoryResponse")]
        WebApplication1.ServiceReference1.MenuItemCategory AddMenuItemCategory(int managerId, string name, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItemCategory", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItemCategoryResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItemCategory> AddMenuItemCategoryAsync(int managerId, string name, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItemCategory", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItemCategoryResponse")]
        bool EditMenuItemCategory(int managerId, WebApplication1.ServiceReference1.MenuItemCategory menuItemCategoryToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItemCategory", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItemCategoryResponse")]
        System.Threading.Tasks.Task<bool> EditMenuItemCategoryAsync(int managerId, WebApplication1.ServiceReference1.MenuItemCategory menuItemCategoryToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItemCategory", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItemCategoryResponse")]
        bool RemoveMenuItemCategory(int managerId, int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItemCategory", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItemCategoryResponse")]
        System.Threading.Tasks.Task<bool> RemoveMenuItemCategoryAsync(int managerId, int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItem", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItemResponse")]
        WebApplication1.ServiceReference1.MenuItem AddMenuItem(int managerId, string name, string description, int categoryId, WebApplication1.ServiceReference1.Money price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItem", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddMenuItemResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItem> AddMenuItemAsync(int managerId, string name, string description, int categoryId, WebApplication1.ServiceReference1.Money price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItem", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItemResponse")]
        bool EditMenuItem(int managerId, WebApplication1.ServiceReference1.MenuItem menuItemToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItem", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditMenuItemResponse")]
        System.Threading.Tasks.Task<bool> EditMenuItemAsync(int managerId, WebApplication1.ServiceReference1.MenuItem menuItemToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItem", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItemResponse")]
        bool RemoveMenuItem(int managerId, int menuItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItem", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveMenuItemResponse")]
        System.Threading.Tasks.Task<bool> RemoveMenuItemAsync(int managerId, int menuItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddWaiter", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddWaiterResponse")]
        WebApplication1.ServiceReference1.UserContext AddWaiter(int managerId, string firstName, string lastName, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddWaiter", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddWaiterResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext> AddWaiterAsync(int managerId, string firstName, string lastName, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditWaiter", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditWaiterResponse")]
        bool EditWaiter(int managerId, WebApplication1.ServiceReference1.UserContext waiterToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditWaiter", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditWaiterResponse")]
        System.Threading.Tasks.Task<bool> EditWaiterAsync(int managerId, WebApplication1.ServiceReference1.UserContext waiterToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveWaiter", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveWaiterResponse")]
        bool RemoveWaiter(int managerId, int waiterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveWaiter", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveWaiterResponse")]
        System.Threading.Tasks.Task<bool> RemoveWaiterAsync(int managerId, int waiterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/GetWaiters", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/GetWaitersResponse")]
        WebApplication1.ServiceReference1.UserContext[] GetWaiters(int managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/GetWaiters", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/GetWaitersResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext[]> GetWaitersAsync(int managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddTable", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddTableResponse")]
        WebApplication1.ServiceReference1.Table AddTable(int managerId, int tableNumber, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/AddTable", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/AddTableResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Table> AddTableAsync(int managerId, int tableNumber, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditTable", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditTableResponse")]
        bool EditTable(int managerId, WebApplication1.ServiceReference1.Table tableToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/EditTable", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/EditTableResponse")]
        System.Threading.Tasks.Task<bool> EditTableAsync(int managerId, WebApplication1.ServiceReference1.Table tableToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveTable", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveTableResponse")]
        bool RemoveTable(int managerId, int tableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveTable", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveTableResponse")]
        System.Threading.Tasks.Task<bool> RemoveTableAsync(int managerId, int tableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/GetOrders", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/GetOrdersResponse")]
        WebApplication1.ServiceReference1.Order[] GetOrders(int managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/GetOrders", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/GetOrdersResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Order[]> GetOrdersAsync(int managerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveOrder", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveOrderResponse")]
        bool RemoveOrder(int managerId, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerDataAccessWCFService/RemoveOrder", ReplyAction="http://tempuri.org/IManagerDataAccessWCFService/RemoveOrderResponse")]
        System.Threading.Tasks.Task<bool> RemoveOrderAsync(int managerId, int orderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagerDataAccessWCFServiceChannel : WebApplication1.ServiceReference1.IManagerDataAccessWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagerDataAccessWCFServiceClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IManagerDataAccessWCFService>, WebApplication1.ServiceReference1.IManagerDataAccessWCFService {
        
        public ManagerDataAccessWCFServiceClient() {
        }
        
        public ManagerDataAccessWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagerDataAccessWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerDataAccessWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerDataAccessWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ServiceReference1.UserContext LogIn(string login1, string password) {
            return base.Channel.LogIn(login1, password);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext> LogInAsync(string login, string password) {
            return base.Channel.LogInAsync(login, password);
        }
        
        public bool LogOut(int id) {
            return base.Channel.LogOut(id);
        }
        
        public System.Threading.Tasks.Task<bool> LogOutAsync(int id) {
            return base.Channel.LogOutAsync(id);
        }
        
        public WebApplication1.ServiceReference1.MenuItemCategory[] GetMenuItemCategories(int userId) {
            return base.Channel.GetMenuItemCategories(userId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItemCategory[]> GetMenuItemCategoriesAsync(int userId) {
            return base.Channel.GetMenuItemCategoriesAsync(userId);
        }
        
        public WebApplication1.ServiceReference1.MenuItem[] GetMenuItems(int userId) {
            return base.Channel.GetMenuItems(userId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItem[]> GetMenuItemsAsync(int userId) {
            return base.Channel.GetMenuItemsAsync(userId);
        }
        
        public WebApplication1.ServiceReference1.Table[] GetTables(int userId) {
            return base.Channel.GetTables(userId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Table[]> GetTablesAsync(int userId) {
            return base.Channel.GetTablesAsync(userId);
        }
        
        public WebApplication1.ServiceReference1.UserContext AddManager(string firstName, string lastName, string login, string password) {
            return base.Channel.AddManager(firstName, lastName, login, password);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext> AddManagerAsync(string firstName, string lastName, string login, string password) {
            return base.Channel.AddManagerAsync(firstName, lastName, login, password);
        }
        
        public WebApplication1.ServiceReference1.MenuItemCategory AddMenuItemCategory(int managerId, string name, string description) {
            return base.Channel.AddMenuItemCategory(managerId, name, description);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItemCategory> AddMenuItemCategoryAsync(int managerId, string name, string description) {
            return base.Channel.AddMenuItemCategoryAsync(managerId, name, description);
        }
        
        public bool EditMenuItemCategory(int managerId, WebApplication1.ServiceReference1.MenuItemCategory menuItemCategoryToEdit) {
            return base.Channel.EditMenuItemCategory(managerId, menuItemCategoryToEdit);
        }
        
        public System.Threading.Tasks.Task<bool> EditMenuItemCategoryAsync(int managerId, WebApplication1.ServiceReference1.MenuItemCategory menuItemCategoryToEdit) {
            return base.Channel.EditMenuItemCategoryAsync(managerId, menuItemCategoryToEdit);
        }
        
        public bool RemoveMenuItemCategory(int managerId, int categoryId) {
            return base.Channel.RemoveMenuItemCategory(managerId, categoryId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveMenuItemCategoryAsync(int managerId, int categoryId) {
            return base.Channel.RemoveMenuItemCategoryAsync(managerId, categoryId);
        }
        
        public WebApplication1.ServiceReference1.MenuItem AddMenuItem(int managerId, string name, string description, int categoryId, WebApplication1.ServiceReference1.Money price) {
            return base.Channel.AddMenuItem(managerId, name, description, categoryId, price);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.MenuItem> AddMenuItemAsync(int managerId, string name, string description, int categoryId, WebApplication1.ServiceReference1.Money price) {
            return base.Channel.AddMenuItemAsync(managerId, name, description, categoryId, price);
        }
        
        public bool EditMenuItem(int managerId, WebApplication1.ServiceReference1.MenuItem menuItemToEdit) {
            return base.Channel.EditMenuItem(managerId, menuItemToEdit);
        }
        
        public System.Threading.Tasks.Task<bool> EditMenuItemAsync(int managerId, WebApplication1.ServiceReference1.MenuItem menuItemToEdit) {
            return base.Channel.EditMenuItemAsync(managerId, menuItemToEdit);
        }
        
        public bool RemoveMenuItem(int managerId, int menuItemId) {
            return base.Channel.RemoveMenuItem(managerId, menuItemId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveMenuItemAsync(int managerId, int menuItemId) {
            return base.Channel.RemoveMenuItemAsync(managerId, menuItemId);
        }
        
        public WebApplication1.ServiceReference1.UserContext AddWaiter(int managerId, string firstName, string lastName, string login, string password) {
            return base.Channel.AddWaiter(managerId, firstName, lastName, login, password);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext> AddWaiterAsync(int managerId, string firstName, string lastName, string login, string password) {
            return base.Channel.AddWaiterAsync(managerId, firstName, lastName, login, password);
        }
        
        public bool EditWaiter(int managerId, WebApplication1.ServiceReference1.UserContext waiterToEdit) {
            return base.Channel.EditWaiter(managerId, waiterToEdit);
        }
        
        public System.Threading.Tasks.Task<bool> EditWaiterAsync(int managerId, WebApplication1.ServiceReference1.UserContext waiterToEdit) {
            return base.Channel.EditWaiterAsync(managerId, waiterToEdit);
        }
        
        public bool RemoveWaiter(int managerId, int waiterId) {
            return base.Channel.RemoveWaiter(managerId, waiterId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveWaiterAsync(int managerId, int waiterId) {
            return base.Channel.RemoveWaiterAsync(managerId, waiterId);
        }
        
        public WebApplication1.ServiceReference1.UserContext[] GetWaiters(int managerId) {
            return base.Channel.GetWaiters(managerId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.UserContext[]> GetWaitersAsync(int managerId) {
            return base.Channel.GetWaitersAsync(managerId);
        }
        
        public WebApplication1.ServiceReference1.Table AddTable(int managerId, int tableNumber, string description) {
            return base.Channel.AddTable(managerId, tableNumber, description);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Table> AddTableAsync(int managerId, int tableNumber, string description) {
            return base.Channel.AddTableAsync(managerId, tableNumber, description);
        }
        
        public bool EditTable(int managerId, WebApplication1.ServiceReference1.Table tableToEdit) {
            return base.Channel.EditTable(managerId, tableToEdit);
        }
        
        public System.Threading.Tasks.Task<bool> EditTableAsync(int managerId, WebApplication1.ServiceReference1.Table tableToEdit) {
            return base.Channel.EditTableAsync(managerId, tableToEdit);
        }
        
        public bool RemoveTable(int managerId, int tableId) {
            return base.Channel.RemoveTable(managerId, tableId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveTableAsync(int managerId, int tableId) {
            return base.Channel.RemoveTableAsync(managerId, tableId);
        }
        
        public WebApplication1.ServiceReference1.Order[] GetOrders(int managerId) {
            return base.Channel.GetOrders(managerId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Order[]> GetOrdersAsync(int managerId) {
            return base.Channel.GetOrdersAsync(managerId);
        }
        
        public bool RemoveOrder(int managerId, int orderId) {
            return base.Channel.RemoveOrder(managerId, orderId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveOrderAsync(int managerId, int orderId) {
            return base.Channel.RemoveOrderAsync(managerId, orderId);
        }
    }
}
